version: "3.8"

services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    restart: always
    volumes:
      - wordpress_files:/var/www/html
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_TITLE=${WP_TITLE}
      - WP_URL=${WP_URL}
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - inception
    env_file:
      - .env

volumes:
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      device: /home/kali/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/kali/data/mariadb
      o: bind

networks:
  inception:
