version: "3.8"

services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    restart: always
    volumes:
      - wordpress_files:/var/www/html
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      db_password:
        file: ../secrets/db_password.txt
      credentials:
        file: ../secrets/credentials.txt
    networks:
      - inception
    depends_on:
      - mariadb



  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      # Inject password manually through setup.sh script
    secrets:
      - db_password.txt
      - db_root_password.txt
    networks:
      - inception

volumes:
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      device: /home/kali/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/kali/data/mariadb
      o: bind

networks:
  inception:

secrets:
  credentials.txt:
    file: ../secrets/credentials.txt
  db_password.txt:
    file: ../secrets/db_password.txt
  db_root_password.txt:
    file: ../secrets/db_root_password.txt
